# Generated by Django 5.0.2 on 2025-05-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="fcm_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
