# Generated by Django 5.0.2 on 2025-03-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_teacher_address_teacher_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="gradehistory",
            name="action",
            field=models.CharField(
                choices=[
                    ("update", "Cập nhật"),
                    ("delete", "Xóa"),
                    ("create", "Tạo mới"),
                ],
                default="update",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="gradehistory",
            name="new_value",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
