# Generated by Django 5.0.2 on 2025-04-17 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_student_phone_student_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="classroom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.classroom",
            ),
        ),
    ]
