# Generated by Django 5.0.2 on 2025-04-17 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_student_classroom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="core.student",
            ),
        ),
    ]
