# tên của workflows
name: Django CI
# sự kiện gì sảy ra thì sẽ chạy
on:
  # setup là push thì chạy job
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
# định nghĩa các công việc tự động chạy
jobs:
  # tên này có thể đặt bất kì
  build:
    # trên máy ảo chạy hệ điều hành gì
    runs-on: ubuntu-latest
    # vì có nhiều version nên nó sẽ mặc định chạy ứng dụng của mình trên python 3.7, 3.8, 3.9
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]
    # cụ thể các bước github action này thực thi
    steps:
    # github action tool kit thì có tất cả các lệnh chỉ cần gọi thoi
    # checkout code là máy ảo phải kéo code mình về kiểm tra
    - uses: actions/checkout@v4
    # tên của steps
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        # lấy lần lượt python-version ở trên
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
